### ISSUE TITLE
Backup deployments - system datastores without non-persistent disks...

### ISSUE THREAD

**Issue by agnetroot** [OpenNebula/addon-image-backup#1]
I used this instruction
https://github.com/OpenNebula/addon-image-backup

I have non-persistent and persistent VMs and images.

When I ran one-image-backup.js for test I got this message

[root@srv_nfsen addon-image-backup]# ./one-image-backup.js -dvD
Backup deployments - system datastores without non-persistent disks...

What's wrong?

**Comment by feldsam** [comment]
Looks like no images was selected. Have XML RPC user enough permissions?

**Comment by agnetroot** [comment]
[root@srvnod32 .ssh]# oneuser show oneadmin
USER 0 INFORMATION
ID              : 0
NAME            : oneadmin
GROUP           : oneadmin
PASSWORD        : хххххххх4633e7a0fe0b01d387209b6хххххххх
AUTH_DRIVER     : core
ENABLED         : Yes

TOKENS

USER TEMPLATE
TOKEN_PASSWORD="ххххххххcbd3b2170af3b2695034a2caхххххххх"

RESOURCE USAGE & QUOTAS

**Comment by feldsam** [comment]
Mine looks same

    [root@engine1 ~]# oneuser show oneadmin
    USER 0 INFORMATION                                                              
    ID              : 0                   
    NAME            : oneadmin            
    GROUP           : oneadmin            
    PASSWORD        : xxxxxxxxxxxxxxxxxxxxx
    AUTH_DRIVER     : core                
    ENABLED         : Yes                 
    
    TOKENS                                                                          
    
    USER TEMPLATE                                                                   
    SUNSTONE=[
      DEFAULT_VIEW="admin",
      LANG="en_US",
      TABLE_DEFAULT_PAGE_LENGTH="100",
      TABLE_ORDER="desc" ]
    TOKEN_PASSWORD="xxxxxxxxxxxxxxxxxxxxx"
    VNC_WSS="no"
    
    RESOURCE USAGE & QUOTAS

**Comment by agnetroot** [comment]
What do you think I need to add or fix? Thanks

**Comment by feldsam** [comment]
Hmm, on images/datastores listing I used -2 filter flag which means `-2: All resources`

When you login to sunstone by oneadmin user, you see all images and datastores?

**Comment by agnetroot** [comment]
Yes. I'm seeing images and datastores

**Comment by agnetroot** [comment]
![image](https://user-images.githubusercontent.com/8327672/36021481-bba1507c-0da7-11e8-81a5-3b0d356591bd.png)

**Comment by feldsam** [comment]
I use this addon https://github.com/OpenNebula/addon-nodejs

Can you try to write simple js cript which selects images via xml-rpc?

**Comment by agnetroot** [comment]
hm. 
I suppose not

**Comment by feldsam** [comment]
Create some directory `mkdir one-test` and switch to it 'cd one-test'

Install nodejs oepnnebula addon `npm install opennebula`

Create new file `nano main.js` and paste following contents to it and set correct api address, user and pass

```
var OpenNebula = require('opennebula');
var one = new OpenNebula('user:hash', 'http://myone.one:2633/RPC2');

one.getDatastores(function(err, data) {
  if(err) {
    return console.log(err);
  }
  console.log(data);
});

one.getImages(function(err, data) {
  if(err) {
    return console.log(err);
  }
  console.log(data);
}, -2);
```

**Comment by agnetroot** [comment]
[root@srv_nfsen addon-image-backup]# ./images-list.js
[ { ID: '0',
    UID: '0',
    GID: '0',
    UNAME: 'oneadmin',
    GNAME: 'oneadmin',
    NAME: 'system',
    PERMISSIONS:
     { OWNER_U: '1',
       OWNER_M: '1',
       OWNER_A: '0',
       GROUP_U: '1',
       GROUP_M: '0',
       GROUP_A: '0',
       OTHER_U: '0',
       OTHER_M: '0',
       OTHER_A: '0' },
    DS_MAD: '-',
    TM_MAD: 'ssh',
    BASE_PATH: '/var/lib/one//datastores/0',
    TYPE: '1',
    DISK_TYPE: '0',
    STATE: '0',
    CLUSTERS: '',
    TOTAL_MB: '0',
    FREE_MB: '0',
    USED_MB: '0',
    IMAGES: '',
    TEMPLATE:
     { ALLOW_ORPHANS: 'NO',
       DISK_TYPE: 'FILE',
       DS_MIGRATE: 'YES',
       RESTRICTED_DIRS: '/',
       SAFE_DIRS: '/var/tmp',
       SHARED: 'NO',
       TM_MAD: 'ssh',
       TYPE: 'SYSTEM_DS' } },
  { ID: '1',
    UID: '0',
    GID: '0',
    UNAME: 'oneadmin',
    GNAME: 'oneadmin',
    NAME: 'default',
    PERMISSIONS:
     { OWNER_U: '1',
       OWNER_M: '1',
       OWNER_A: '0',
       GROUP_U: '1',
       GROUP_M: '0',
       GROUP_A: '0',
       OTHER_U: '0',
       OTHER_M: '0',
       OTHER_A: '0' },
    DS_MAD: 'fs',
    TM_MAD: 'ssh',
    BASE_PATH: '/var/lib/one//datastores/1',
    TYPE: '0',
    DISK_TYPE: '0',
    STATE: '0',
    CLUSTERS: '',
    TOTAL_MB: '51175',
    FREE_MB: '47503',
    USED_MB: '3673',
    IMAGES: '',
    TEMPLATE:
     { ALLOW_ORPHANS: 'NO',
       CLONE_TARGET: 'SYSTEM',
       DISK_TYPE: 'FILE',
       DS_MAD: 'fs',
       LN_TARGET: 'SYSTEM',
       RESTRICTED_DIRS: '/',
       SAFE_DIRS: '/var/tmp',
       TM_MAD: 'ssh',
       TYPE: 'IMAGE_DS' } },
  { ID: '2',
    UID: '0',
    GID: '0',
    UNAME: 'oneadmin',
    GNAME: 'oneadmin',
    NAME: 'files',
    PERMISSIONS:
     { OWNER_U: '1',
       OWNER_M: '1',
       OWNER_A: '0',
       GROUP_U: '1',
       GROUP_M: '0',
       GROUP_A: '0',
       OTHER_U: '0',
       OTHER_M: '0',
       OTHER_A: '0' },
    DS_MAD: 'fs',
    TM_MAD: 'ssh',
    BASE_PATH: '/var/lib/one//datastores/2',
    TYPE: '2',
    DISK_TYPE: '0',
    STATE: '0',
    CLUSTERS: '',
    TOTAL_MB: '51175',
    FREE_MB: '47503',
    USED_MB: '3673',
    IMAGES: '',
    TEMPLATE:
     { ALLOW_ORPHANS: 'NO',
       CLONE_TARGET: 'SYSTEM',
       DS_MAD: 'fs',
       LN_TARGET: 'SYSTEM',
       RESTRICTED_DIRS: '/',
       SAFE_DIRS: '/var/tmp',
       TM_MAD: 'ssh',
       TYPE: 'FILE_DS' } },
  { ID: '104',
    UID: '0',
    GID: '0',
    UNAME: 'oneadmin',
    GNAME: 'oneadmin',
    NAME: 'cephds',
    PERMISSIONS:
     { OWNER_U: '1',
       OWNER_M: '1',
       OWNER_A: '0',
       GROUP_U: '1',
       GROUP_M: '0',
       GROUP_A: '0',
       OTHER_U: '0',
       OTHER_M: '0',
       OTHER_A: '0' },
    DS_MAD: 'ceph',
    TM_MAD: 'ceph',
    BASE_PATH: '/var/lib/one//datastores/104',
    TYPE: '0',
    DISK_TYPE: '3',
    STATE: '0',
    CLUSTERS: { ID: '100' },
    TOTAL_MB: '226579',
    FREE_MB: '199551',
    USED_MB: '27028',
    IMAGES: { ID: [Object] },
    TEMPLATE:
     { ALLOW_ORPHANS: 'YES',
       BRIDGE_LIST: '172.19.100.4 172.19.100.1 172.19.100.2',
       CEPH_HOST: '172.19.100.4:6789 172.19.100.1:6789 172.19.100.2:6789',
       CEPH_SECRET: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
       CEPH_USER: 'libvirt',
       CLONE_TARGET: 'SELF',
       DISK_TYPE: 'RBD',
       DRIVER: 'raw',
       DS_MAD: 'ceph',
       LN_TARGET: 'NONE',
       POOL_NAME: 'one',
       RESTRICTED_DIRS: '/',
       SAFE_DIRS: '/var/tmp',
       TM_MAD: 'ceph' } },
  { ID: '105',
    UID: '0',
    GID: '0',
    UNAME: 'oneadmin',
    GNAME: 'oneadmin',
    NAME: 'CephSystem',
    PERMISSIONS:
     { OWNER_U: '1',
       OWNER_M: '1',
       OWNER_A: '0',
       GROUP_U: '1',
       GROUP_M: '0',
       GROUP_A: '0',
       OTHER_U: '0',
       OTHER_M: '0',
       OTHER_A: '0' },
    DS_MAD: '-',
    TM_MAD: 'ceph',
    BASE_PATH: '/var/lib/one//datastores/105',
    TYPE: '1',
    DISK_TYPE: '0',
    STATE: '0',
    CLUSTERS: { ID: '100' },
    TOTAL_MB: '226579',
    FREE_MB: '199551',
    USED_MB: '27028',
    IMAGES: '',
    TEMPLATE:
     { ALLOW_ORPHANS: 'YES',
       BRIDGE_LIST: '172.19.100.4 172.19.100.1 172.19.100.2',
       CEPH_HOST: '172.19.100.4:6789 172.19.100.1:6789 172.19.100.2:6789',
       CEPH_SECRET: '67185e10-6441-4a15-8a42-e371ade22f33',
       CEPH_USER: 'libvirt',
       DISK_TYPE: 'FILE',
       DS_MIGRATE: 'NO',
       POOL_NAME: 'one',
       RESTRICTED_DIRS: '/',
       SAFE_DIRS: '/var/tmp',
       SHARED: 'YES',
       TM_MAD: 'ceph',
       TYPE: 'SYSTEM_DS' } } ]
[ { ID: '102',
    UID: '2',
    GID: '0',
    UNAME: 'ag',
    GNAME: 'oneadmin',
    NAME: 'srvalpha-disk',
    PERMISSIONS:
     { OWNER_U: '1',
       OWNER_M: '1',
       OWNER_A: '1',
       GROUP_U: '0',
       GROUP_M: '0',
       GROUP_A: '0',
       OTHER_U: '0',
       OTHER_M: '0',
       OTHER_A: '0' },
    TYPE: '0',
    DISK_TYPE: '3',
    PERSISTENT: '0',
    REGTIME: '1514284600',
    SOURCE: 'one/one-102',
    PATH: '/var/tmp/3147038720-srvalpha',
    FSTYPE: 'raw',
    SIZE: '20480',
    STATE: '2',
    RUNNING_VMS: '1',
    CLONING_OPS: '0',
    CLONING_ID: '-1',
    TARGET_SNAPSHOT: '-1',
    DATASTORE_ID: '104',
    DATASTORE: 'cephds',
    VMS: { ID: '71' },
    CLONES: '',
    APP_CLONES: '',
    TEMPLATE: { DEV_PREFIX: 'sd', DRIVER: 'qcow2' },
    SNAPSHOTS: { ALLOW_ORPHANS: 'NO' } },
  { ID: '107',
    UID: '2',
    GID: '0',
    UNAME: 'ag',
    GNAME: 'oneadmin',
    NAME: 'srvbravo.qcow2',
    PERMISSIONS:
     { OWNER_U: '1',
       OWNER_M: '1',
       OWNER_A: '0',
       GROUP_U: '0',
       GROUP_M: '0',
       GROUP_A: '0',
       OTHER_U: '0',
       OTHER_M: '0',
       OTHER_A: '0' },
    TYPE: '0',
    DISK_TYPE: '3',
    PERSISTENT: '1',
    REGTIME: '1514532335',
    SOURCE: 'one/one-107',
    PATH: '/var/tmp/2291073024-srvbravoqcow2',
    FSTYPE: 'raw',
    SIZE: '20480',
    STATE: '1',
    RUNNING_VMS: '0',
    CLONING_OPS: '0',
    CLONING_ID: '-1',
    TARGET_SNAPSHOT: '-1',
    DATASTORE_ID: '104',
    DATASTORE: 'cephds',
    VMS: '',
    CLONES: '',
    APP_CLONES: '',
    TEMPLATE: { DEV_PREFIX: 'sd', DRIVER: 'qcow2' },
    SNAPSHOTS: { ALLOW_ORPHANS: 'NO' } },
  { ID: '118',
    UID: '2',
    GID: '0',
    UNAME: 'ag',
    GNAME: 'oneadmin',
    NAME: 'vm1-disk-0',
    PERMISSIONS:
     { OWNER_U: '1',
       OWNER_M: '1',
       OWNER_A: '0',
       GROUP_U: '0',
       GROUP_M: '0',
       GROUP_A: '0',
       OTHER_U: '0',
       OTHER_M: '0',
       OTHER_A: '0' },
    TYPE: '0',
    DISK_TYPE: '3',
    PERSISTENT: '1',
    REGTIME: '1515750081',
    SOURCE: 'one/one-118',
    PATH: 'one/one-110',
    FSTYPE: 'raw',
    SIZE: '20480',
    STATE: '8',
    RUNNING_VMS: '1',
    CLONING_OPS: '0',
    CLONING_ID: '-1',
    TARGET_SNAPSHOT: '-1',
    DATASTORE_ID: '104',
    DATASTORE: 'cephds',
    VMS: { ID: '66' },
    CLONES: '',
    APP_CLONES: '',
    TEMPLATE: { DEV_PREFIX: 'hd', DRIVER: 'raw', FSTYPE: 'raw' },
    SNAPSHOTS: { ALLOW_ORPHANS: 'YES', SNAPSHOT: [Object] } },
  { ID: '122',
    UID: '2',
    GID: '0',
    UNAME: 'ag',
    GNAME: 'oneadmin',
    NAME: 'vmsrvbravo-disk-0',
    PERMISSIONS:
     { OWNER_U: '1',
       OWNER_M: '1',
       OWNER_A: '0',
       GROUP_U: '0',
       GROUP_M: '0',
       GROUP_A: '0',
       OTHER_U: '0',
       OTHER_M: '0',
       OTHER_A: '0' },
    TYPE: '0',
    DISK_TYPE: '3',
    PERSISTENT: '1',
    REGTIME: '1516617068',
    SOURCE: 'one/one-122',
    PATH: 'one/one-107',
    FSTYPE: 'raw',
    SIZE: '20480',
    STATE: '8',
    RUNNING_VMS: '1',
    CLONING_OPS: '0',
    CLONING_ID: '-1',
    TARGET_SNAPSHOT: '-1',
    DATASTORE_ID: '104',
    DATASTORE: 'cephds',
    VMS: { ID: '69' },
    CLONES: '',
    APP_CLONES: '',
    TEMPLATE: { DEV_PREFIX: 'sd', DRIVER: 'qcow2', FSTYPE: 'raw' },
    SNAPSHOTS: { ALLOW_ORPHANS: 'NO' } },
  { ID: '123',
    UID: '2',
    GID: '0',
    UNAME: 'ag',
    GNAME: 'oneadmin',
    NAME: 'srv_ansible.qcow2',
    PERMISSIONS:
     { OWNER_U: '1',
       OWNER_M: '1',
       OWNER_A: '0',
       GROUP_U: '0',
       GROUP_M: '0',
       GROUP_A: '0',
       OTHER_U: '0',
       OTHER_M: '0',
       OTHER_A: '0' },
    TYPE: '0',
    DISK_TYPE: '3',
    PERSISTENT: '0',
    REGTIME: '1516624008',
    SOURCE: 'one/one-123',
    PATH: '/var/tmp/21478375424-srv_ansibleqcow2',
    FSTYPE: 'qcow2',
    SIZE: '20480',
    STATE: '1',
    RUNNING_VMS: '0',
    CLONING_OPS: '0',
    CLONING_ID: '-1',
    TARGET_SNAPSHOT: '-1',
    DATASTORE_ID: '104',
    DATASTORE: 'cephds',
    VMS: '',
    CLONES: '',
    APP_CLONES: '',
    TEMPLATE: { DEV_PREFIX: 'sd', DRIVER: 'qcow2' },
    SNAPSHOTS: { ALLOW_ORPHANS: 'NO' } },
  { ID: '124',
    UID: '2',
    GID: '0',
    UNAME: 'ag',
    GNAME: 'oneadmin',
    NAME: 'srv_ansible-disk-0',
    PERMISSIONS:
     { OWNER_U: '1',
       OWNER_M: '1',
       OWNER_A: '0',
       GROUP_U: '0',
       GROUP_M: '0',
       GROUP_A: '0',
       OTHER_U: '0',
       OTHER_M: '0',
       OTHER_A: '0' },
    TYPE: '0',
    DISK_TYPE: '3',
    PERSISTENT: '1',
    REGTIME: '1516626826',
    SOURCE: 'one/one-124',
    PATH: 'one/one-123',
    FSTYPE: 'qcow2',
    SIZE: '20480',
    STATE: '8',
    RUNNING_VMS: '1',
    CLONING_OPS: '0',
    CLONING_ID: '-1',
    TARGET_SNAPSHOT: '-1',
    DATASTORE_ID: '104',
    DATASTORE: 'cephds',
    VMS: { ID: '70' },
    CLONES: '',
    APP_CLONES: '',
    TEMPLATE: { DEV_PREFIX: 'sd', DRIVER: 'qcow2', FSTYPE: 'qcow2' },
    SNAPSHOTS: { ALLOW_ORPHANS: 'NO' } },
  { ID: '125',
    UID: '2',
    GID: '0',
    UNAME: 'ag',
    GNAME: 'oneadmin',
    NAME: 'alphatest',
    PERMISSIONS:
     { OWNER_U: '1',
       OWNER_M: '1',
       OWNER_A: '0',
       GROUP_U: '0',
       GROUP_M: '0',
       GROUP_A: '0',
       OTHER_U: '0',
       OTHER_M: '0',
       OTHER_A: '0' },
    TYPE: '0',
    DISK_TYPE: '3',
    PERSISTENT: '0',
    REGTIME: '1517835021',
    SOURCE: 'one/one-125',
    PATH: '/var/tmp/3147038720-srv_alphaqcow2',
    FSTYPE: 'qcow2',
    SIZE: '20480',
    STATE: '1',
    RUNNING_VMS: '0',
    CLONING_OPS: '0',
    CLONING_ID: '-1',
    TARGET_SNAPSHOT: '-1',
    DATASTORE_ID: '104',
    DATASTORE: 'cephds',
    VMS: '',
    CLONES: '',
    APP_CLONES: '',
    TEMPLATE: { DEV_PREFIX: 'vd', DRIVER: 'qcow2' },
    SNAPSHOTS: { ALLOW_ORPHANS: 'NO' } } ]

**Comment by feldsam** [comment]
I see, in my script is check for datastore TM_MAD == qcow2. But you use SSH and CEPH.

I see that you su CEPH RBD, which is not supported by this script.

This script works file, when you have filesystem datastore and images are stored as qcow2 files. So for simple not clustered ext4 datastores or clustered filesystems like GFS2 

I think, that this script can be modified to work with CEPH RBD, for ex. can be implemented use of this python script https://github.com/camptocamp/ceph-rbd-backup

It need some work and testing, I don't have CEPH cluster deployed, so I can't test it.

**Comment by agnetroot** [comment]
OK. Thanks Kristian
