### ISSUE TITLE
Running the script but nothing happens

### ISSUE THREAD

**Issue by astronode** [OpenNebula/addon-image-backup#2]
I have followed your guide on getting the OpenNebula backup script working but can’t seem to get any output from it.
When I run it, it doesn’t display or do anything. I can’t see any errors eithers.
I have installed all the pre-requisites, tested the RPC and SSH connection to the node and front-end. Not sure what I’m doing wrong.
 
Your help would be much appreciated!
 
Many thanks,
Vasily

**Comment by feldsam** [comment]
hmm, have you node installed in `/usr/local/bin/node`? try to run it by calling `node one-image-backup.js -d`

**Comment by astronode** [comment]
I made a link from /usr/local/bin/node to the actual location.
Tried prefixing node to the command but still nothing, no output whatsoever.
Without the dry run option I get "Do you really want execute backup? If not, use --dry-run option (yes/no) [no]:" but after that still nothing happens.
Running OpenNebula 5.4.12.

**Comment by feldsam** [comment]
Add between lines 70 and 72 this snippet

```
one.version(function(err, data) {
  console.log(data);
  process.exit(0);
  });
```

So we can test if connection to one is sucess or not.

**Comment by astronode** [comment]
Added it, then I get the output - 5.4.12

**Comment by feldsam** [comment]
So connection is working. What type of datastores you use? This script only support datastore TM_MAD == qcow2

**Comment by astronode** [comment]
That's probably it - we're using SSH datastores, with qcow2 images.
How can I modify the script to work with them? Or would it need a complete redesign?
We use independent hypervisors with local storage.

**Comment by astronode** [comment]
Yes TM_MAD = ssh.
Many thanks! Looking forward to testing it.

**Comment by feldsam** [comment]
Hello, any news? I like to complete this issue

**Comment by astronode** [comment]
Hi Kristian, sorry for the delay, we had to switch to local scripts on hypervisors to get the backup going and decommissioned the backup server for the time being. I will update you when I get a chance to reopen the project. Thanks again for your help.
