### ISSUE TITLE
Feature Request - Option for domfstrim

### ISSUE THREAD

**Issue by ulide4** [OpenNebula/addon-image-backup#3]
Hello Feldsam,

it is possible to trigger a fstrim through the qemu-guest-agent with "virsh -c qemu:///system domfstrim ...".
It would be great if you could add an option to do a domfstrim before the image transfer. This could save bandwidth and storage space at the backup storage.

Thanks & Best Regards
Uli

**Comment by feldsam** [comment]
Hello @ulide4 please test feature, so I can make release and close this issue. Thanks

**Comment by feldsam** [comment]
Version 1.8.0 released
